spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Student
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: School
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false # Not registering Eureka with itself to avoid cyclic dependencies.

